# Generated by Django 5.2.6 on 2025-09-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.IntegerField()),
                ('gender', models.CharField()),
                ('dob', models.DateField()),
                ('course', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='pictures')),
                ('aadhar', models.ImageField(upload_to='pictures')),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('fee', models.CharField(max_length=255)),
            ],
        ),
    ]
